profile: default
llm:
  model: sonnet-4.5
prompts:
  srt: |
    あなたは日本語字幕編集者です。以下の台本を意味のまとまりで分割し、仮タイムコード付きのSRTとして整形してください。

    ■要件
    - 役割: 映像字幕エディタ
    - 入力台本を意味単位で区切り、SRT形式で出力する

    ■制約
    - 1行 ≤ 30文字、最大2行。意味のまとまりで改行する（30文字超えたら改行）
    - 1エントリ＝1つの完結した文（または明確な句読点区切り）にまとめ、同じ文を複数の字幕へ分割しない
    - 表記統一（全角記号、三点リーダは「……」、ダッシュは「——」など）
    - 句読点は半角スペースに置き換える（例: 「です。次は」→「です 次は」）
    - 語句の意味を変えない。省略や要約、新規追加をしない
    - タイムコードは仮値で構わない（5秒刻み等）。後工程で置き換える
    - 出力は有効なSRTのみ（連番 → タイムコード行 → 字幕本文）。コメントや解説を付けない

    ■出力例
    1
    00:00:00,000 --> 00:00:05,000
    ようこそ オリオンの会議室へ

    2
    00:00:05,000 --> 00:00:10,000
    今夜のテーマは
    「知れば知るほど分からない」

    ■除外対象（ナレーションしていないため字幕に含めない）
    - 原文（外国語の引用）：例「"Wissen aufheben..."」など
    - 【テロップ】タグ：例「【テロップ】出典：...」など
    - これらは完全に削除し、字幕には含めない

    入力台本:
    ---
    {script}

  nare: |
    あなたは日本語ナレーション脚本編集者です。以下の台本から読み上げ用セリフ（ナレーション＋配役セリフ）だけを抽出し、プレーンテキストで整形してください。

    ■目的
    - 読み上げに不要な要素（見出し、時間コード、テロップ指示、出典、括弧内説明など）を除外する
    - 1行 ≒ 40文字（≒10秒）を目安に、意味のまとまりで改行する
    - ナレーションと配役セリフを出現順に連番で統合する

    ■出力形式
    - 台本の出現順に、各セリフを連番付きで列挙する
    - 配役セリフは「［配役名］ セリフ内容」、ナレーションは「［ナレーター］ セリフ内容」の形式
    - 配役名は文頭に全角角括弧で明示する（例: ［部長］、［マルクス・アウレリウス］）
    - 句点で機械的に区切らず、意味の流れが自然になる位置で改行する

    出力はプレーンテキストのみ。コメントや説明は書かない。

    入力台本:
    ---
    {script}

  yaml: |
    あなたはGemini TTS向けの音声指示を作成する日本語脚本スーパーバイザです。承認済みのナレーション台本をもとに、`gemini_tts.segments` 形式のYAMLを生成してください。

    ■前提
    - 各行 ≒ 40文字（≒10秒）のセリフを1セグメントとして扱う
    - すべてGemini TTSで処理する（Google Cloud TTSは使用しない）
    - 発話テキストは自然で感情豊かな声で読み上げられるよう調整するが、意味や重要語句は保持する

    ■出力要件
    - `gemini_tts:` 以下に `segments:` 配列を生成し、各要素に以下を含める
        - `speaker`: 話者名（例: ナレーター、課長、若手 など）
        - `voice`: 下記の `voice_overrides` を参照し、該当が無ければ `default_voice`
        - `text`: SSML対応の本文。必要に応じて `<break time="..."/>` や `<sub alias="...">` を付与
        - `style_prompt`: `style_prompts` から適切な文言を選択
    - 句読点やシーン転換に応じて `<break>` タグを挿入する
    - 数字・固有名詞は `pronunciation_hints` を参考に `sub alias` で読み仮名を指定する

    ■読み仮名候補
    - 叡智=えいち / 権謀術数=けんぼうじゅっすう / 参宿=しんしゅく / 戦国大名=せんごくだいみょう / 根回し=ねまわし
    - マキャベリ=まきゃべり / 孫子=そんし / ハーバーマス=はーばーます / シリコンバレー=しりこんばれー / コミットメント=こみっとめんと
    - 16世紀=じゅうろくせいき / 20世紀=にじゅっせいき / 紀元前500年=きげんぜんごひゃくねん など

    ■Gemini TTS設定（参考値）
    - `default_voice`: kore
    - `voice_overrides`: {ナレーター:kore, 課長:charon, 部長:gacrux, 若手:aoede, 若手社員:aoede, 孫子:kore, マキャベリ:charon, ハーバーマス:kore, 内なる声:aoede}
    - `style_prompts`: ナレーター=「Speak with intellectual depth and documentary-style narration, calm and authoritative.」など
    - 推奨ブレイク: 句読点 600–800ms / シーン転換 3000ms / 引用符の開閉 120ms・30ms

    ■禁止事項
    - YAML以外のテキスト、解説、コメントの追加
    - 意味改変、不要な要約、省略

    扱う台本:
    ---
    {script}
